### ISSUE TITLE
Setup PR testing for build-pipeline unit tests

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#15]
## Expected Behavior
Every PR should have unit tests run against it automatically.

(The long term dream is that we use the Pipeline CRD reference implementation _itself_ to test this repo, but since it is just an API right now, that's a ways off!)

## Actual Behavior
We have no automation! Is master broken? WHO KNOWS IT'S A CRAZY WORLD 🤠

## Steps to Reproduce the Problem

  1. Open a PR with broken unit tests
  2. Notice that nothing catches this

To actually run the tests:

```bash
make test
```

(see also the [DEVELOPMENT.md](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#running-tests))

## Additional Info

We would be fine with using something like Travis initially, but it would have to be enabled for the entire `knative` org, and since the rest of the org is using Prow, we can probably jump on that train.

Configuration for Prow for the other knative projects lives in https://github.com/knative/test-infra/tree/master/ci/prow

**Comment by adrcunha** [comment]
* See https://github.com/knative/test-infra/blob/master/ci/prow/prow_setup.md%23setting-up-prow-for-a-new-repo for more details on setting up the Prow jobs.
* Travis is not a supported CI/CD for Knative.
* Kubernetes Prow docs are a nice reference, but since Knative has his own Prow instance, not all steps apply.

**Comment by bobcatfish** [comment]
Whoa i dunno how this stayed open so long, this was done ages ago :D
