### ISSUE TITLE
Add Build status fields to TaskRun status

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#236]
## Expected Behavior
Similar to the work being done in #228, we should add the status fields which `Build` is using to `TaskRun.status`, so that we can show this status information to a user without requiring the user be aware of the `Build` which has been created, and go find it.

These fields should mirror the status of the underlying `Build`.

This should not include the Builder and Cluster fields, which are now obsolete/

## Actual Behavior

The status fields in `TaskRun` are pretty sparse, and one has to look up the associated `Build` to see what is happening as the `TaskRun` executes.

## Additional Info
* Similar to the work being done in #228
* Part of #147

**Comment by vdemeester** [comment]
To make sure I'm going in the right direction it's : 
- Adding what is in `knative/build` BuildStatus type into `TaskRunStatus`
- Update how it gets populate (and populate the field the same way `knative/build` does)

am I missing sthg ?

**Comment by pivotal-nader-ziada** [comment]
@vdemeester I think you are on the right track, did you get started on a PR yet?

**Comment by vdemeester** [comment]
@pivotal-nader-ziada started to work on it, didn't want to open a PR until I have a tiny bit of sthg that make sense

**Comment by ImJasonH** [comment]
While you're moving fields from `BuildStatus` to `TaskRunStatus`, we can take the opportunity to remove warts from the API. Namely, we should drop `status.Builder` (since it's always `Cluster` today), and we should probably drop the `status.Cluster` struct and just move `status.Cluster.PodName` up to `status.PodName`.

While a `TaskRun` creates and watches a `Build` it should just update its fields directly from what the `BuildStatus` has whenever it's updated. When `TaskRun` becomes responsible for creating `Pod`s itself, we can change `BuildStatusFromPod` to `TaskRunStatusFromPod`, which should mostly be a rename. `BuildStatusFromPod` is added in https://github.com/knative/build/pull/464

**Comment by vdemeester** [comment]
> This should not include the Builder and Cluster fields, which are now obsolete/

@ImJasonH ok :angel:

**Comment by bobcatfish** [comment]
Thanks @vdemeester !! :heart:
