### ISSUE TITLE
Using parallel option with `gsutil` image causes errors to make Tasks hang

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#372]
## Expected Behavior
If you try to use [the gcs storage resource](https://github.com/knative/build-pipeline/blob/master/docs/using.md#gcs-storage-resource) and `gsutil` (used for uploading) encounters an error, the `Task` using the output should fail with a meaningful error.

## Actual Behavior

Using `-m` (which runs `gsutil` command in parallel) with gsutil inside a container causes `gsutil` to hang when an error is encountered and the error is not propagated to the user.

If the `gsutil` command succeeds, there is no problem, which is why we didn't notice this before.

This doesn't seem to happen when running an installation of `gsutil` directly; only when running it in a container (and maybe only when running it in `google/cloud-sdk:alpine` ? not sure!).

The underlying problem is almost definitely in `gsutil` itself (or the way the image is built).

## Steps to Reproduce the Problem

Run this command on a machine with docker installed (note you will need to `docker kill` the process and it will steal your terminal):

```
docker run google/cloud-sdk:alpine gsutil -m cp /notarealpath gs://this-is-not-a-bucket-dddd
```

Note that the command will just hang :( If you exec into the image you will see a number of python processes just hanging out.

However if you remove the `-m` option the container will print a meaningful error and exit:

```
docker run google/cloud-sdk:alpine gsutil cp /notarealpath gs://this-is-not-a-bucket-dddd 
CommandException: No URLs matched: /notarealpath
```

## Additional Info
Thanks (and also sorry :sweat_smile: ) @mgreau for reporting this!

**Comment by mgreau** [comment]
> This doesn't seem to happen when running an installation of gsutil directly; only when running it in a container (and maybe only when running it in google/cloud-sdk:alpine ? not sure!).

I'm using the Knative Build Pipeline nightly release published on `1/5/19, 9:50:17 AM UTC+1`  and this version uses a container with `gsutil version: 4.34`.

Looking at the [bugs fixed in the latest `gsutil` release](https://github.com/GoogleCloudPlatform/gsutil/blob/d76b30e218fd0daa2c4fbafc26cdc64d3d82048a/CHANGES.md#bug-fixes) (**Release 4.35 - release date: 2018-12-18**), it seems this problem has been fixed with https://github.com/GoogleCloudPlatform/gsutil/commit/d7493e711e5b1c1937d0e57a25544bfba2641eb4

Now that we can override the [gsutil base image ](https://github.com/knative/build-pipeline/commit/11594f85c6499d0fe6b15da293e43b593abce228) I will try by using an image with `gsutil version: 4.35`
