### ISSUE TITLE
copy the labels from `Task` ->`TaskRun` to the generated Pod

### ISSUE THREAD

**Issue by jstrachan** [knative/build-pipeline#458]
## Expected Behavior

If we add labels to a `Task` they should get replicated to the `TaskRun` then the `Pod` thats created so that you can more easily query/filter TaskRuns and Pods.

## Actual Behavior

Labels on a `Task` are ignored

If there are concerns over copying the labels, maybe there could be a way to specify which labels to copy/not copy?

**Comment by dwnusbaum** [comment]
I'm actually picking this up from Andrew :) Looking at the code, propagation from PipelineRun to TaskRun to Pod (through Build in memory) is pretty trivial, but propagation from Task through to Pod is a little trickier because right now most of the relevant data structures only pass a TaskSpec around but we'd need to full Task or at least its metadata. I discussed with @jstrachan and he was ok with leaving out Task for now if it requires significant extra work, but noted that it would be ideal to be able to use a single label to obtain all resources related to a build.

**Comment by bobcatfish** [comment]
It feels kinda like the chain should go all the way:

* Pipeline -> PipelineRun -> TaskRun -> pod
* Task -> TaskRun -> pod

What do you think?

> I'm actually picking this up from Andrew :)

Hooray!! :tada: :D

> most of the relevant data structures only pass a TaskSpec around but we'd need to full Task or at least its metadata.

hm good point - I'm sure we can figure out a way to make it work :D in the worse case we could always use the Task client to retrieve the Task again :thinking: - but also adding the labels to the [resolved task resources](https://github.com/knative/build-pipeline/blob/master/pkg/reconciler/v1alpha1/taskrun/resources/taskresourceresolution.go#L25) or similar might not be too bad?

> but noted that it would be ideal to be able to use a single label to obtain all resources related to a build.

@dwnusbaum relevant note, @tanner-bruce actually added a bit of label propagation in #199 (see [the docs here](https://github.com/tanner-bruce/build-pipeline/blob/c9540c5a7e2c85a81314a5ed0ebf0d2d2f9d0a47/docs/using.md#troubleshooting) which for my sins I deleted in #460 because I couldn't figure out where to put them :innocent: (not a very good excuse)

**Comment by bobcatfish** [comment]
lol totally late to the party and the PR, sorry @dwnusbaum :rofl:

**Comment by bobcatfish** [comment]
I am really tempted to put in a last request to add some docs on this but considering that I deleted the last ones I wouldn't blame you if you ignored me @dwnusbaum :sweat_smile: :sweat_smile: :sweat_smile: 

(in retrospect I should not have deleted them...)

**Comment by dwnusbaum** [comment]
> It feels kinda like the chain should go all the way

Yeah I agree, it was just really easy to add the *Run propagation so I went for that first. Do you think it makes sense to open another issue specifically for Pipeline and Task label propagation, or just reopen this one? (I don't have permission to update the title/description so it might be cleaner to use a new issue)

> but also adding the labels to the [resolved task resources](https://github.com/knative/build-pipeline/blob/master/pkg/reconciler/v1alpha1/taskrun/resources/taskresourceresolution.go#L25) or similar might not be too bad?

Yeah, that was what I was thinking too, but it seemed like at that point we might as well just have the whole Task in case anything needed additional metadata in the future. From my quick look it seemed like there was no particular reason that we dropped the Task and just carried around the TaskSpec, so it would just be a matter of tweaking the struct and fixing up the use sites, but maybe I was missing something. Definitely deserves a closer look!

> I am really tempted to put in a last request to add some docs on this

Yeah that seems fair to me 😄 I will try to whip something up from what was added in #199 and explain that custom labels are supported in addition to the labels we add to everything automatically. I am working on updating the e2e tests to check label propagation as well so I'll probably submit a PR for all of that.

**Comment by dwnusbaum** [comment]
e2e tests updated and docs added in #500

**Comment by bobcatfish** [comment]
> e2e tests updated and docs added in #500

niiiiiice 🙏 😍 

> Do you think it makes sense to open another issue specifically for Pipeline and Task label propagation, or just reopen this one?

A new issue is probably more satisfying too! :D

**Comment by dwnusbaum** [comment]
> A new issue is probably more satisfying too! :D

Created #501 😄
