### ISSUE TITLE
Can't specify any arbitrary commit id in git resource

### ISSUE THREAD

**Issue by pivotal-nader-ziada** [knative/build-pipeline#543]
## Expected Behavior
Use the revision param in the git resource to specify any arbitrary commit should pull the git repo at this commit

## Actual Behavior
specifying a commit hash in the `revision` param results in an error 
```
error: Server does not allow request for unadvertised object 0b4133b...26bd2e2d
``` 

## Steps to Reproduce the Problem

1. Use a git resource with an commit hash in the revision param

## Additional Info

From slack by @duane
```
Further to @Adam Roberts’s question above, one of the things we noticed during prototyping with build-pipeline was that you couldn't specify any arbitrary commit id ..... as the cmd/git-init/main.go does a git fetch (and you end up with errors about getting unadvertised commits)..... searching around on the web, there seemed to be various references to git properties you might be able to set on the server side to get unadvertised commits but I couldn't seem to get things working.

Interested to know if there is some magic I am missing - or if a code change is needed here.  To get around it, I forked the code and modified the code to do ....

```run(logger, "git", "pull", "--recurse-submodules=yes", "origin")
runOrFail(logger, "git", "checkout", *revision)```


seems to pass the go tests and happy to create PR to contribute, but thought I should check if I'm missing something in terms of using ANY commit id.  Additionally, no doubt we could argue about performance regarding fetch and pull .... the error you will get doing a pull with no branch listed (although the pull succeeds) .... and whether there should be an additional property to revision and path where you can specify a commit id ... and then if a commitid is specified do the git pull otherwise do the git fetch???
```

**Comment by ImJasonH** [comment]
This is the same as https://github.com/knative/build/issues/212

Basically, GitHub (and most-but-not-all other Git hosting services) don't serve commits that aren't pointed to by branches or tags.

The workaround will probably be to have fetch-by-commit do a full clone instead of a shallow clone, then checkout the requested commit. This will be slower than doing the shallow clone, especially for large repos with lots of history, but at least it will work.

**Comment by pivotal-nader-ziada** [comment]
One suggestion I have is to add another optional param to the git resource for the commit hash, and if that is provided do the `git pull` otherwise do the `fetch` to be more efficient. We might want to rename the `revision` to `branch` with that approach.

**Comment by ImJasonH** [comment]
The reason Build chose the term `revision` was that it's used as a general term for any of a branch/tag/commit, or any ref at all like `refs/pull/123` which is the ref for a pull request.

We could split those out into four separate mutually-exclusive fields, but we thought it's a somewhat simpler API to just accept one string and use Git's consistent and documented logic for determining whether a revision is a branch/tag/ref/commit (like when you do `git checkout <thing>`).

If we decide to detect and handle commits differently than branches/tags/refs, we probably shouldn't match the regex of a commit SHA (possibly partial SHA) ahead of time since someone could be referring to a branch named `deadbeef`. Instead, we should attempt the shallow fetch then fallback to the full clone+checkout if we see that specific error.

**Comment by bobcatfish** [comment]
> We could split those out into four separate mutually-exclusive fields, but we thought it's a somewhat simpler API to just accept one string and use Git's consistent and documented logic for determining whether a revision is a branch/tag/ref/commit (like when you do `git checkout <thing>`).

If we don't want to add additional fields, another option would be to catch the initial error and try to do a `pull` + `checkout` in that case

**Comment by bobcatfish** [comment]
From the chat in slack, sounds like @dibbles is going to take this on! :heart: :tada:

**Comment by dibbles** [comment]
Yes - I'll look at getting something together for this.

**Comment by dibbles** [comment]
Well, if we don't go down the path of adding the different options - then I think we need to retry using a pull on any error from the fetch.  I'm not sure we can check for the error given as different git providers might give different errors..... therefore I'm looking at adding something along the lines of:

```
        err = run(logger, "git", "fetch", "--depth=1", "--recurse-submodules=yes", "origin", *revision)
	if err != nil {
		// Fetch can fail if an old commitid was used so try git pull, performing regardless of error
		// as no guarantee that the same error is returned by all git servers gitlab, github etc...
		run(logger, "git", "pull", "--recurse-submodules=yes", "origin")
		runOrFail(logger, "git", "checkout", *revision)
	} else {
		runOrFail(logger, "git", "reset", "--hard", "FETCH_HEAD")
	}
```

Also looking at adding in some tests - hope to have something together in a PR this week.
