### ISSUE TITLE
Add Pipeline Label to pipelineRun and tasksRun 

### ISSUE THREAD

**Issue by pivotal-nader-ziada** [knative/build-pipeline#69]
## Expected Behavior

The `PipelineRun` and `TasksRun` object  should have a label with the pipeline name. Can be called  `knative.dev/pipeline` with a value of the actual pipeline name. 

The TaskRun controller can use the Pipeline name in Pod metadata and log messages. 

## Actual Behavior

Currently there are no labels added

## Additional Info
 * The PR to add this functionality should add an integration test to validate labels are propagating correctly 
 * Similar example in [serving](https://github.com/knative/serving/blob/b707183d8355544c3cd8e841923eb08ccb91ceba/pkg/apis/serving/register.go) and the [Spec](https://github.com/knative/serving/blob/master/docs/spec/spec.md) for it
 * Should we have any other labels? such as `Task` name label on the `TaskRun`?

**Comment by pivotal-nader-ziada** [comment]
One example is the `taskRun` pod can include the pipeline name and task name in the logs to make it easier to filter these logs

**Comment by tejal29** [comment]
Are you also thinking of adding PipelineRun label to TaskRun in this task?

**Comment by pivotal-nader-ziada** [comment]
It would make sense to add the `PipelineRun` name as a label on the `TaskRun`

**Comment by bobcatfish** [comment]
Okay I looked into our options a bit about how to reference child resources (e.g. a `PipelineRun`'s `TaskRuns`, a `TaskRun` owns a `Build`) (slightly expanding the scope of this task :sweat_smile: ), looking at 4 options:

1. Labels (e.g. `knative.dev/pipelinerun: kritis-pipeline-run-12321312984`)
2. Using [OwnerReferences](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/)
3. Using `ObjectReferences`
4. Using the names of the child resources

### Labels

Inside a controller we can use the informer's `Lister()` to list by label:

```go
	// Try getting the related TaskRuns by label, using the name of this PipelineRun
	selector := labels.SelectorFromSet(map[string]string{"knative.dev/pipelinerun": key})
	taskRuns, err := c.taskRunLister.TaskRuns(namespace).List(selector)
	if err != nil {
		c.Logger.Errorf("Error retrieving TaskRuns by label for %s", key)
	} else {
		for _, tr := range taskRuns {
			c.Logger.Infof("THIS IS MY TASK RUN %v", tr.GetName())
		}
	}
```

### OwnerReferences

As far as I can tell it's not possible to query for all objects with a particular owner reference. I found these two thread requesting this feature:

- https://github.com/kubernetes/kubernetes/issues/54498
- https://github.com/kubernetes/kubernetes/issues/49387#issuecomment-382730124 (requests via FieldSelectors)

Which is unfortunate since this is pretty much exactly what we're looking for!

### ObjectReferences

I completely forgot that in our `PipelineRun` schema, we actually already have references to the created TaskRuns:

https://github.com/knative/build-pipeline/blob/f9d5590b53aede86384259a8a4d15adec2002a81/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go#L70

The go type is a bit incomplete, but [in the yaml](https://github.com/knative/build-pipeline/blob/f9d5590b53aede86384259a8a4d15adec2002a81/examples/invocations/kritis-pipeline-run.yaml#L14) you can see what we were getting at:

![image](https://user-images.githubusercontent.com/432502/46564815-94c3c700-c8be-11e8-8004-5fbf65bfe09c.png)

### Names

* Since `TaskRuns` and `Builds` have a 1:1 mapping, it probably makes sense to use the same name for both
* In `PipelineRuns`, we can construct a deterministic name by combining the name of the `PipelineRun` and the name of the `Task` inside the referenced `Pipeline`

So we could query for the child resources by name, though it seems that fuzzy or regex based searching isn't clearly possible (apparently https://github.com/kubernetes/kubernetes/issues/9248#issuecomment-108958065 that's what labels are for :rofl:) - even though it is actually [supported by the describe command](https://github.com/kubernetes/kubernetes/issues/10674).

@tejal29 pointed out there is some complication here tho - what do we want to do if the same `PipelineRun` or `TaskRun` (i.e. with the same name) is invoked? To work around that we could add a random element to the names, or alternatively we could require the Runs have unique names.

## Conclusion

I suggest that when retrieving child resources in the `PipelineRun` controllers, we use references to `TaskRuns` in the `Status`, since we'll need those anyway (the controller will need to know which it has started).

I think sticking to using the same name for the `TaskRun` and its child `Build` (which @aaron-prindle is already doing).

But as @pivotal-nader-ziada pointed out, it can be handy for the controllers when logging to know about what created them, and @tejal29 also pointed out it's handy on the command line to retrieve all related `TaskRuns` for example, so I think we should add:

* `PipelineRun`: 
  * `knative.dev/pipeline` - can added by `PipelineRun` controller
* `TaskRun`:
  * `knative.dev/pipeline` - if this was triggered by a `PipelineRun`, the related pipeline
  * `knative.dev/pipelineRun` - if this was triggered by a `PipelineRun`
* `Build`:
  * `knative.dev/pipeline` - if this was triggered by a `PipelineRun`, the related pipeline
  * `knative.dev/pipelineRun` - if this was triggered by a `PipelineRun`
  * `knative.dev/taskRun` - if this was triggered by a `TaskRun` (even tho the name will be the same)

I'll add these to the existing controllers as they get to the point where they can be added, unless they are added by folks working on those controllers before I get a chance.

(let me know if you want any more added!)

**Comment by bobcatfish** [comment]
I'm gonna unassign myself from this since I haven't gotten a chance to work on it: the work to do here is to add the labels as described in the previous comment.
